### ISSUE TITLE
Something about this plugin causes issues for QGIS locator bar

### ISSUE THREAD

**Issue by AlisterH** [Jannik-Schilling/WaterNetAnalyzer#3]
```
2020-08-17T10:08:11     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\gui\AlgorithmLocatorFilter.py", line 90, in fetchResults
              tags = [*a.tags(), a.provider().name(), a.group()]
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\WaterNetAnalyzer-master\Water_Netw_Constructor.py", line 325, in group
              return self.tr()
             TypeError: tr() missing 1 required positional argument: 'string'
             
2020-08-17T10:08:13     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\gui\AlgorithmLocatorFilter.py", line 90, in fetchResults
              tags = [*a.tags(), a.provider().name(), a.group()]
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\WaterNetAnalyzer-master\Water_Netw_Constructor.py", line 325, in group
              return self.tr()
             TypeError: tr() missing 1 required positional argument: 'string'
             
2020-08-17T10:08:27     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins\processing\gui\AlgorithmLocatorFilter.py", line 90, in fetchResults
              tags = [*a.tags(), a.provider().name(), a.group()]
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\WaterNetAnalyzer-master\Water_Netw_Constructor.py", line 325, in group
              return self.tr()
             TypeError: tr() missing 1 required positional argument: 'string'
```

**Comment by AlisterH** [comment]
Sorry, just realised this instance didn't have the latest version of the plugin.  I will reopen if I see it again.
